### PR TITLE
User & Roles persistence: basic entities, DTOs, DAOs

### PR DESCRIPTION
**Pull request by kateNemochka**
Issue #6 (Design Model)

### CODE REVIEW

**Comment by kateNemochka** [comment]
> 1. DTO`s should have methods that transfer data from entity to DTO and vice versa.

Shouldn't DTO be a POJO class (the one that only has constructors and getters/setters)?

**Comment by tezzi2001** [comment]
> > 1. DTO`s should have methods that transfer data from entity to DTO and vice versa.
> 
> Shouldn't DTO be a POJO class (the one that only has constructors and getters/setters)?

POJO is an ordinary Java object, not bound by any special restriction. By restriction implies inheritance in most cases.

**Comment by kateNemochka** [comment]
Closing to make new pull request

**Comment by tezzi2001** [comment]
Everything is fine.

**Pull request merged**
